version: '3.8'

services:
  app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tenderdb?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenderdb
    ports:
      - "5680:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local