server:
  port: 8888

database:
  postgres:
    port: 5432
    host: "localhost"
    password: "postgres"
    username: "postgres"
    db_name: "postgres"
  redis:
    address: "localhost:6379"
    password:
    db_name: 0  