server:
  port: 8888

database:
  postgres:
    port: 5432
    host: "db"
    password: "postgres"
    username: "postgres"
    db_name: "tenderdb"
  redis:
    address: "redis:6379"
    password:
    db_name: 0